### ISSUE TITLE
Put moves in separate files

### ISSUE THREAD

**Issue by G710** [SmilieGames/stone-age-reloaded#2]
Damit am Ende nicht alle Aktionen und Logikberechnungen in einem Hash stehen, würde ich diese gerne auslagern. Also folgendes Dateiverzeichnisstruktur:
```
-src
  -components
    StoneAge.js
    StoneAgeRenderer.js
    -moves
      agrar.js
      stone.js
etc...
```
In `StoneAge.js` werden dann diese Parts nur noch aufgerufen und wieder zusammengefuehrt.
```
StoneAge.js

import AgrarMoves from './moves/AgrarMoves'
(....)
  moves: {
    ...AgrarMoves,
    ...StoneMoves,
  }
etc...
```

Was haelst du davon?

**Comment by Kompethemd** [comment]
Neue Dateien für moves wurden angelegt. Diese sind nach view gegliedert. Da in der Villageansicht die AddCitizen and Remove überall die gleiche Struktur haben kann das zu einer Funktion zusammengeführt werden:
addCitizensToAgrar(G, selectedStation, ctx){
    if(G[selectedStation]. < G.agrar.maxCitizens && G[selectedStation].currentCitizens > 0){
      G[selectedStation].currentCitizens++;
      G.village.currentCitizens--;
    }
  },
  removeCitizensFromAgrar(G, selectedStation, ctx){
    if(G[selectedStation].currentCitizens > 0){
      G[selectedStation].currentCitizens--;
      G.village.currentCitizens++;
    }
  }

**Comment by Kompethemd** [comment]
see comment before. new files have been added
